import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

// POST: Save pre-generated quiz questions for a document
// Quiz questions are generated by Claude Code during content prep — no API key needed
export async function POST(request: Request) {
  try {
    const { document_id, questions } = await request.json();

    if (!document_id || !questions) {
      return NextResponse.json(
        { error: 'document_id and questions are required' },
        { status: 400 }
      );
    }

    // Delete any existing quiz for this document (replace with fresh one)
    await supabase.from('quizzes').delete().eq('document_id', document_id);

    // Store the quiz
    const { data: quiz, error } = await supabase
      .from('quizzes')
      .insert({ document_id, questions })
      .select()
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(quiz);
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
